---
apiVersion: kontinue.io/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain-simple
spec:
  selector:
    app.tanzu.vmware.com/workload-type: simple

  components:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image
      sources:
        - component: source-provider
          name: source

    - name: app-runner
      templateRef:
        kind: ClusterTemplate
        name: kn-app
      images:
        - component: image-builder
          name: image
