---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: demo
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/go
    - image: gcr.io/paketo-buildpacks/nodejs
    - image: gcr.io/paketo-buildpacks/java
